config/routes.rb
Rails.application.routes.draw do
    
  resources :dokters
  resources :transaksi_obats
  resources :obat_masuks
  resources :reseps
  resources :rekam_mediks
  resources :kunjungans
  resources :pasiens
  resources :kartu_rms
  resources :penyakits
  resources :obats
  resources :jenis_penyakits
  resources :jenis_kartus
  resources :kelurahans
  resources :polis
  resources :kategoris
    root 'sessions#new'

    get '/help' =>'static_pages#help'
    get '/home' =>'static_pages#home'
    get '/signup' => 'admins#new'
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    delete '/logout' => 'sessions#destroy'
    get 'search_pasien' => 'pasiens#search'
    get 'search_obat_masuk' => 'obats#search_obat_masuk'
    get 'search_obat_keluar' => 'obats#search_obat_keluar'
    get 'cetak_rekam_medik' => 'pasiens#rekam_medik'
    get 'lb2' => 'obats#laporan'
    get 'lb1' => 'pasiens#laporan'
    get 'cetak_lb1' => 'pasiens#cetak_laporan'
    get 'cetak_lb2' => 'obats#cetak_laporan'
  resources :admins

end

app/models/dokter.rb
class Dokter < ActiveRecord::Base
    has_many :rekam_mediks
end

app/controllers/dokters_controller.rb
class DoktersController < ApplicationController
  before_action :set_dokter, only: [:show, :edit, :update, :destroy]

  # GET /dokters
  # GET /dokters.json
  def index
    @dokters = Dokter.all
  end

  # GET /dokters/1
  # GET /dokters/1.json
  def show
  end

  # GET /dokters/new
  def new
    @dokter = Dokter.new
  end

  # GET /dokters/1/edit
  def edit
  end

  # POST /dokters
  # POST /dokters.json
  def create
    @dokter = Dokter.new(dokter_params)

    respond_to do |format|
      if @dokter.save
        format.html { redirect_to @dokter, notice: 'Dokter was successfully created.' }
        format.json { render :show, status: :created, location: @dokter }
      else
        format.html { render :new }
        format.json { render json: @dokter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dokters/1
  # PATCH/PUT /dokters/1.json
  def update
    respond_to do |format|
      if @dokter.update(dokter_params)
        format.html { redirect_to @dokter, notice: 'Dokter was successfully updated.' }
        format.json { render :show, status: :ok, location: @dokter }
      else
        format.html { render :edit }
        format.json { render json: @dokter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dokters/1
  # DELETE /dokters/1.json
  def destroy
    @dokter.destroy
    respond_to do |format|
      format.html { redirect_to dokters_url, notice: 'Dokter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dokter
      @dokter = Dokter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dokter_params
      params.require(:dokter).permit(:nama)
    end
end

app/helpers/dokters_helper.rb
module DoktersHelper
end

app/views/dokters/_form.html.erb
<%= simple_form_for(@dokter) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nama %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/dokters/edit.html.erb
<h1>Editing Dokter</h1>

<%= render 'form' %>

<%= link_to 'Show', @dokter %> |
<%= link_to 'Back', dokters_path %>

app/views/dokters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dokters</h1>

<table>
  <thead>
    <tr>
      <th>Nama</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dokters.each do |dokter| %>
      <tr>
        <td><%= dokter.nama %></td>
        <td><%= link_to 'Show', dokter %></td>
        <td><%= link_to 'Edit', edit_dokter_path(dokter) %></td>
        <td><%= link_to 'Destroy', dokter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dokter', new_dokter_path %>

app/views/dokters/new.html.erb
<h1>New Dokter</h1>

<%= render 'form' %>

<%= link_to 'Back', dokters_path %>

app/views/dokters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nama:</strong>
  <%= @dokter.nama %>
</p>

<%= link_to 'Edit', edit_dokter_path(@dokter) %> |
<%= link_to 'Back', dokters_path %>