config/routes.rb
Rails.application.routes.draw do
    
  resources :dokters
  resources :transaksi_obats
  resources :obat_masuks
  resources :reseps
  resources :rekam_mediks
  resources :kunjungans
  resources :pasiens
  resources :kartu_rms
  resources :penyakits
  resources :obats
  resources :jenis_penyakits
  resources :jenis_kartus
  resources :kelurahans
  resources :polis
  resources :kategoris
    root 'sessions#new'

    get '/help' =>'static_pages#help'
    get '/home' =>'static_pages#home'
    get '/signup' => 'admins#new'
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    delete '/logout' => 'sessions#destroy'
    get 'search_pasien' => 'pasiens#search'
    get 'search_obat_masuk' => 'obats#search_obat_masuk'
    get 'search_obat_keluar' => 'obats#search_obat_keluar'
    get 'cetak_rekam_medik' => 'pasiens#rekam_medik'
    get 'lb2' => 'obats#laporan'
    get 'lb1' => 'pasiens#laporan'
    get 'cetak_lb1' => 'pasiens#cetak_laporan'
    get 'cetak_lb2' => 'obats#cetak_laporan'
  resources :admins

end

app/models/rekam_medik.rb
class RekamMedik < ActiveRecord::Base
    belongs_to :pasien
  belongs_to :penyakit
    belongs_to :dokter
    after_create :diagnosa
    validates :keluhan, presence: true
    validates :penyakit_id, presence: true

    
    def diagnosa
        b = Kunjungan.where(:pasien_id => self.pasien_id, :created_at => (self.created_at.beginning_of_day..self.created_at.end_of_day)).first
            new_a = KunjunganMedik.new
            new_a.pasien_id = self.pasien_id
            new_a.kunjungan = b.kunjungan
            new_a.penyakit_id = self.penyakit_id
            new_a.save
    end
end

app/controllers/rekam_mediks_controller.rb
class RekamMediksController < ApplicationController
  before_action :set_rekam_medik, only: [:show, :edit, :update, :destroy]
    before_action :logged_in_user, only: [:new, :create, :update, :destroy, :index, :show, :edit]

    
  # GET /rekam_mediks
  # GET /rekam_mediks.json
  def index
    @rekam_mediks = RekamMedik.all
  end

  # GET /rekam_mediks/1
  # GET /rekam_mediks/1.json
  def show
  end

  # GET /rekam_mediks/new
  def new
    @rekam_medik = RekamMedik.new
  end

  # GET /rekam_mediks/1/edit
  def edit
  end

  # POST /rekam_mediks
  # POST /rekam_mediks.json
  def create
    @rekam_medik = RekamMedik.new(rekam_medik_params)

    respond_to do |format|
      if @rekam_medik.save
          format.html { redirect_to pasien_path(@rekam_medik.pasien), notice: 'Rekam medik was successfully created.' }
#          format.json { render :show, status: :created, location: @pasien}
      else
        format.html { render :new }
        format.json { render json: @rekam_medik.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rekam_mediks/1
  # PATCH/PUT /rekam_mediks/1.json
  def update
    respond_to do |format|
      if @rekam_medik.update(rekam_medik_params)
        format.html { redirect_to @rekam_medik, notice: 'Rekam medik was successfully updated.' }
        format.json { render :show, status: :ok, location: @rekam_medik }
      else
        format.html { render :edit }
        format.json { render json: @rekam_medik.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rekam_mediks/1
  # DELETE /rekam_mediks/1.json
  def destroy
    @rekam_medik.destroy
    respond_to do |format|
        format.html { redirect_to pasiens_url, notice: 'Rekam medik was successfully destroyed.' }
      format.json { head :no_content }
#        redirect_to :back
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rekam_medik
      @rekam_medik = RekamMedik.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rekam_medik_params
        params.require(:rekam_medik).permit(:pasien_id, :nama, :keluhan, :penyakit_id, :terapi, :tindakan, :dokter_id)
    end
end

app/helpers/rekam_mediks_helper.rb
module RekamMediksHelper
end

app/views/rekam_mediks/_form.html.erb
<div class="col-md-6 col-md-offset-2">
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Entri Rekam Medik</h3>
  </div>
  <div class="panel-body">

<%= simple_form_for(@rekam_medik) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :pasien, selected: params[:no_rm], label_method: :nama, value_method: :id %>
    <%#<%= f.input :nama %>
    <%= f.input :keluhan %>
    <%= f.association :penyakit, label_method: :nama %>
      <%= f.association :dokter, label_method: :nama %>
    <%= f.input :terapi %>
    <%= f.input :tindakan %>
  </div>
<br>
  <div class="form-actions">
      <%#<%= f.hidden_field :pasien_id, value: @rekam_medik.pasien_id %>
      <%= f.button :submit, class: "btn btn-primary", value: "Tambah Rekam Medik" %>
  </div>
<% end %>
      
      
    </div>
    </div>
</div>

app/views/rekam_mediks/edit.html.erb
<h1>Editing Rekam Medik</h1>

<%= render 'form' %>

<%= link_to 'Show', @rekam_medik %> |
<%= link_to 'Back', rekam_mediks_path %>

app/views/rekam_mediks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rekam Mediks</h1>

<table>
  <thead>
    <tr>
      <th>Nama</th>
      <th>Keluhan</th>
      <th>Penyakit</th>
      <th>Terapi</th>
      <th>Tindakan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rekam_mediks.each do |rekam_medik| %>
      <tr>

        <td><%= rekam_medik.nama %></td>
        <td><%= rekam_medik.keluhan %></td>
        <td><%= rekam_medik.penyakit.nama %></td>
        <td><%= rekam_medik.terapi %></td>
        <td><%= rekam_medik.tindakan %></td>
        <td><%= link_to 'Show', rekam_medik %></td>
        <td><%= link_to 'Edit', edit_rekam_medik_path(rekam_medik) %></td>
        <td><%= link_to 'Destroy', rekam_medik, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rekam medik', new_rekam_medik_path %>

app/views/rekam_mediks/new.html.erb
<%= render 'form' %>

app/views/rekam_mediks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Kartu rm:</strong>
    <%= @rekam_medik.pasien.no_rm %>
</p>

<p>
  <strong>Nama:</strong>
  <%= @rekam_medik.nama %>
</p>

<p>
  <strong>Keluhan:</strong>
  <%= @rekam_medik.keluhan %>
</p>

<p>
  <strong>Penyakit:</strong>
  <%= @rekam_medik.penyakit %>
</p>

<p>
  <strong>Terapi:</strong>
  <%= @rekam_medik.terapi %>
</p>

<p>
  <strong>Tindakan:</strong>
  <%= @rekam_medik.tindakan %>
</p>

<%= link_to 'Edit', edit_rekam_medik_path(@rekam_medik) %> |
<%= link_to 'Back', rekam_mediks_path %>