config/routes.rb
Rails.application.routes.draw do
    
  resources :dokters
  resources :transaksi_obats
  resources :obat_masuks
  resources :reseps
  resources :rekam_mediks
  resources :kunjungans
  resources :pasiens
  resources :kartu_rms
  resources :penyakits
  resources :obats
  resources :jenis_penyakits
  resources :jenis_kartus
  resources :kelurahans
  resources :polis
  resources :kategoris
    root 'sessions#new'

    get '/help' =>'static_pages#help'
    get '/home' =>'static_pages#home'
    get '/signup' => 'admins#new'
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    delete '/logout' => 'sessions#destroy'
    get 'search_pasien' => 'pasiens#search'
    get 'search_obat_masuk' => 'obats#search_obat_masuk'
    get 'search_obat_keluar' => 'obats#search_obat_keluar'
    get 'cetak_rekam_medik' => 'pasiens#rekam_medik'
    get 'lb2' => 'obats#laporan'
    get 'lb1' => 'pasiens#laporan'
    get 'cetak_lb1' => 'pasiens#cetak_laporan'
    get 'cetak_lb2' => 'obats#cetak_laporan'
  resources :admins

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  
    before_save { self.email = email.downcase }
    validates :username,
            presence: true,
            uniqueness: true,
            length: { maximum: 50 }
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX }
    has_secure_password
    validates :password, 
            presence: true, 
            length: { minimum: 6 }
    # Returns the hash digest of the given string.
    def Admin.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
    
end

app/models/dokter.rb
class Dokter < ActiveRecord::Base
    has_many :rekam_mediks
end

app/models/jenis_kartu.rb
class JenisKartu < ActiveRecord::Base
    belongs_to :kategori
    has_many :pasiens
    has_many :kartu_rms
    has_many :kunjungans
    
    
end

app/models/jenis_penyakit.rb
class JenisPenyakit < ActiveRecord::Base
    has_many :penyakits
end

app/models/kategori.rb
class Kategori < ActiveRecord::Base
    has_many :jenis_kartus
    has_many :pasiens
    has_many :kunjungans
    
end

app/models/kelurahan.rb
class Kelurahan < ActiveRecord::Base
    has_many :pasiens
    has_many :kunjungans
    
    
end

app/models/kunjungan.rb
class Kunjungan < ActiveRecord::Base
  belongs_to :poli
  belongs_to :kategori
  belongs_to :jenis_kartu
    belongs_to :pasien
    belongs_to :penyakit
    validates :kunjungan, presence: true
    validates :keluhan, presence: true
    validates :poli_id, presence: true

#    after_create :medik
#    after_save :data_pasien
    
    def tanggal
        self.created_at = self.created_at.to_date
    end
    
#    
#    def medik
#        new_medik = KunjunganMedik.new
#        new_medik.pasien_id = self.pasien_id
#        new_medik.kunjungan = self.kunjungan
#        new_medik.save
#    end
#    def data_pasien
#        if (b = Pasien.where(:id => self.pasien_id).first)
#            b.umur=self.umur
#
#            self.save
#        end
#    end
end

app/models/obat.rb
class Obat < ActiveRecord::Base
    has_many :reseps, dependent: :destroy
    has_many :obat_masuks, dependent: :destroy
    has_many :transaksi_obats, dependent: :destroy
    validates :stok_awal, presence: true
    validates :nama, presence: true
    validates :kode, presence: true
    
    before_create :set_stok
#    after_commit :laporan
    
    def set_stok
        self.stok = stok_awal
    end
    
    def self.search(search)
        where("nama LIKE ?", "%#{search}%") 
    end
    

end

app/models/obat_masuk.rb
class ObatMasuk < ActiveRecord::Base
  belongs_to :obat
    after_save :update_obat_stok
    after_create :new_transaksi_obat
    validates :jumlah_masuk, presence: true
    validates :penerimaan, presence: true

    
    def update_obat_stok
        if (b = Obat.where(:id => self.obat_id).first)
        b.stok = self.jumlah_masuk+b.stok
        b.save
    end
    end
    
    def new_transaksi_obat
      new_transaksi = TransaksiObat.new
        new_transaksi.obat_id = self.obat_id
        new_transaksi.jumlah_masuk = self.jumlah_masuk
        new_transaksi.penerimaan = self.penerimaan
        new_transaksi.jumlah_ambil = 0
        new_transaksi.pemakaian = ""
      new_transaksi.save
    end
end

app/models/pasien.rb
class Pasien < ActiveRecord::Base
  belongs_to :kelurahan
  belongs_to :kategori
  belongs_to :jenis_kartu
    has_many :rekam_mediks, dependent: :destroy
    has_many :kunjungans, dependent: :destroy
    has_many :kunjungan_mediks, dependent: :destroy
    validates :no_rm, presence: true
    validates :nama, presence: true
    validates :status, presence: true
    validates :alamat, presence: true
    validates :tanggal_lahir, presence: true
    validates :jenis_kelamin, presence: true
    validates :kategori_id, presence: true


#    after_save :umur_pasien
    
    def self.search(search)
        where("nama LIKE ?", "%#{search}%") 
    end
    
#    def umur_pasien
#        umur=((Date.today - self.tanggal_lahir) / 365).floor
#        save
#    end
    
end

app/models/penyakit.rb
class Penyakit < ActiveRecord::Base
  belongs_to :jenis_penyakit
    has_many :rekam_mediks, dependent: :destroy
    has_many :kunjungans, dependent: :destroy
    has_many :kunjungan_mediks, dependent: :destroy
end

app/models/poli.rb
class Poli < ActiveRecord::Base
    has_many :kunjungans
end

app/models/rekam_medik.rb
class RekamMedik < ActiveRecord::Base
    belongs_to :pasien
  belongs_to :penyakit
    belongs_to :dokter
    after_create :diagnosa
    validates :keluhan, presence: true
    validates :penyakit_id, presence: true

    
    def diagnosa
        b = Kunjungan.where(:pasien_id => self.pasien_id, :created_at => (self.created_at.beginning_of_day..self.created_at.end_of_day)).first
            new_a = KunjunganMedik.new
            new_a.pasien_id = self.pasien_id
            new_a.kunjungan = b.kunjungan
            new_a.penyakit_id = self.penyakit_id
            new_a.save
    end
end

app/models/resep.rb
class Resep < ActiveRecord::Base
  belongs_to :obat
    after_save :update_obat_stok
    after_create :new_transaksi_obat
    validates :jumlah_ambil, presence: true
    validates :pemakaian, presence: true

    
    def update_obat_stok
        if (b = Obat.where(:id => self.obat_id).first)
            b.stok = b.stok-self.jumlah_ambil
            b.save
        end
    end
    
    def new_transaksi_obat
      new_transaksi = TransaksiObat.new
        new_transaksi.obat_id = self.obat_id
        new_transaksi.jumlah_masuk = 0
        new_transaksi.penerimaan = ""
        new_transaksi.jumlah_ambil = self.jumlah_ambil
        new_transaksi.pemakaian = self.pemakaian
      new_transaksi.save
    end
    
#    def total_resep(
#        if (a = Resep.where((:created_at.to_date => self.created_at.to_date) & (:obat_id => self.obat_id)).first)
#            a.jumlah_ambil = self.jumlah_ambil + b.jumlah_ambil
#            a.save
#        end
#    end
    
end

app/models/resep_search.rb
class ResepSearch < ActiveRecord::Base
    
    def initialize(params)
#        params ||= {}
        @date = parsed_date(params[:date], Date.today.to_s)
    end
    
    def scope
        Resep.where('created_at LIKE ?%', @date)
    end
    
    private
    
    def parsed_date(date_string, default)
        Date.parse(date_string)
    rescue ArgumentError, TypeError
        default
    end
    
end

app/models/transaksi_obat.rb
class TransaksiObat < ActiveRecord::Base
    belongs_to :obat
end

app/helpers/admins_helper.rb
module AdminsHelper
    

end

app/helpers/dokters_helper.rb
module DoktersHelper
end

app/helpers/obats_helper.rb
module ObatsHelper
end

app/helpers/pasiens_helper.rb
module PasiensHelper
    

end

app/helpers/polis_helper.rb
module PolisHelper
end

app/helpers/reseps_helper.rb
module ResepsHelper
end

app/views/pasiens/_form.html.erb
<div class="col-md-6 col-md-offset-2">
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Pasien Baru</h3>
  </div>
  <div class="panel-body">
   
      
    <%= simple_form_for(@pasien) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :no_rm %>
    <%#<%= f.association :kartu_rm, selected: params[:no_rm], label_method: :no_rm, value_method: :id %>
    <%= f.input :nama %><br>
    
    <%#<%= f.input  :collection => [[Kepala, 'Kepala Keluarga'], [Anggota, 'Anggota Keluarga']], :label_method => :last, :value_method => :first, :as => :radio_buttons, :item_wrapper_class => 'inline'a %>

    <ul class="list-inline">
            <li>
                <%= f.label :status %>
            </li>
            <li>
                Kepala keluarga
            </li>
            <li>
                <%= f.radio_button :status, 'Kepala' %>
            </li>
            <li>
                Anggota keluarga
            </li>
            <li>
                <%= f.radio_button :status, 'Anggota' %>
            </li>
        </ul>

            
    <%= f.input :alamat %>
    <%= f.association :kelurahan, label_method: :nama %>
    <%= f.label :tanggal_lahir %><br>
    <%= f.date_select :tanggal_lahir, :start_year => Time.now.year - 100, :end_year => Time.now.year, :html_options => {:class => "date-select"} %><br>
      <br>
    
        <ul class="list-inline">
            <li>
                <%= f.label :jenis_kelamin %>
            </li>
            <li>
                L
            </li>
            <li>
                <%= f.radio_button :jenis_kelamin, 'L' %>
            </li>
            <li>
                P
            </li>
            <li>
                <%= f.radio_button :jenis_kelamin, 'P' %>
            </li>
        </ul>
    <%= f.association :kategori, label_method: :nama %>
    <%= f.association :jenis_kartu, label_method: :nama %>
    <%= f.input :no_kartu %>

  </div>
<br>
  <div class="form-actions">
      <%= f.button :submit, class: "btn btn-primary", value:"Tambah Pasien" %>
  </div>
<% end %>

      
      
      
      
      
      
      
  </div>
</div>

</div>

app/views/pasiens/edit.html.erb
<h1>Editing Pasien</h1>

<%= render 'form' %>

<%= link_to 'Show', @pasien %> |
<%= link_to 'Back', pasiens_path %>

app/views/pasiens/index.html.erb
<h1>Daftar Pasien</h1>
<div class="pull-right">
<%= form_tag(pasiens_path, :method => "get", class: "navbar-form navbar-left", role: "search") do %>
<div class="form-group">
    <%= search_field_tag :search, params[:search], class: "form-control", placeholder: "Search Pasien" %>
<%= submit_tag "Search", class: 'btn btn-info' %>
 </div>
<% end %>
</div>
<br>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Kartu rm</th>
      <th>Nama</th>
      <th>Alamat</th>
      <th>Kelurahan</th>
      <th>Umur</th>
      <th>Jenis kelamin</th>
      <th>Kategori</th>
      <th>Jenis kartu</th>
      <th>No kartu</th>
      <th colspan="3">Aksi</th>
    </tr>
  </thead>

  <tbody>
    <% @pasiens.each do |pasien| %>
      <tr>
        <td><%= pasien.no_rm %></td>
        <td><%= pasien.nama %></td>
        <td><%= pasien.alamat %></td>
        <td><%= pasien.kelurahan.nama %></td>
        <td><%= pasien.umur %></td>
        <td><%= pasien.jenis_kelamin %></td>
        <td><%= pasien.kategori.nama %></td>
          <% if pasien.jenis_kartu != nil %>
        <td><%= pasien.jenis_kartu.nama %></td>
          <% else %>
          <td>-</td>
          <% end %>
          <% if pasien.no_kartu != nil %>
        <td><%= pasien.no_kartu %></td>
        <% else %>
          <td>-</td>
          <% end %>
        <td><%= link_to 'Show', pasien %></td>
        <td><%= link_to 'Edit', edit_pasien_path(pasien) %></td>
        <td><%= link_to 'Destroy', pasien, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#<%= link_to 'New Pasien', new_pasien_path %>

app/views/pasiens/laporan.html.erb
<div class="pull-right">
<%= form_tag lb1_path, method: :get do %>
    <div class="input-group">
        <div class="input-group-addon">
    
            <select id="bulan" name="bulan">
              <option value="January">Januari</option>
              <option value="February">Februari</option>
              <option value="March">Maret</option>
              <option value="April">April</option>
              <option value="May">Mei</option>
              <option value="June">Juni</option>
              <option value="July">Juli</option>
              <option value="August">Agustus</option>
              <option value="September">September</option>
              <option value="October">Oktober</option>
              <option value="November">November</option>
              <option value="December">Desember</option>
            </select></div>

        <div class="input-group-addon">
            <select id="tahun" name="tahun">
              <option value="2013">2013</option>
              <option value="2014">2014</option>
              <option value="2015">2015</option>
              <option value="2016">2016</option>
              <option value="2017">2017</option>
                <!--
                  <option value="June">Juni</option>
                  <option value="July">Juli</option>
                  <option value="August">Agustus</option>
                  <option value="September">September</option>
                  <option value="October">Oktober</option>
                  <option value="November">November</option>
                  <option value="December">Desember</option>
                -->
            </select>
        </div>
    </div>
    <%= submit_tag 'Search', class: 'btn search-button' %>
<% end %>
    <br>

</div>
<%= link_to "Cetak Laporan", cetak_lb1_path(:format => "pdf", :bulan => params[:bulan], :tahun => params[:tahun]), :target => "_blank" %>
<table class="table table-bordered">
  <thead>
    <tr>
      <th rowspan="4">Nama Penyakit</th>
      <th rowspan="4">Jenis Penyakit</th>
      <th colspan="36">Jumlah Penderita</th>
      <th colspan="4">Total</th>
      </tr>
      <tr>
      <td colspan="4"><1 Th</td>
      <td colspan="4">1-4 Th</td>
      <td colspan="4">5-9 Th</td>
      <td colspan="4">10-14 Th</td>
      <td colspan="4">15-19 Th</td>
      <td colspan="4">20-44 Th</td>
      <td colspan="4">45-43 Th</td>
      <td colspan="4">55-59 Th</td>
      <td colspan="4">>60 Th</td>
    </tr>
      <tr>
      <td colspan="2">B</td>
      <td colspan="2">L</td>
      <td colspan="2">B</td>
      <td colspan="2">L</td>
      <td colspan="2">B</td>
      <td colspan="2">L</td>
      <td colspan="2">B</td>
      <td colspan="2">L</td>
      <td colspan="2">B</td>
      <td colspan="2">L</td>
      <td colspan="2">B</td>
      <td colspan="2">L</td>
      <td colspan="2">B</td>
      <td colspan="2">L</td>
      <td colspan="2">B</td>
      <td colspan="2">L</td>
      <td colspan="2">B</td>
      <td colspan="2">L</td>
      <td colspan="2">B</td>
      <td colspan="2">L</td>
      </tr>
      <tr>
      <td>L</td>
      <td>P</td>
      <td>L</td>
      <td>P</td>
      <td>L</td>
      <td>P</td>
      <td>L</td>
      <td>P</td>
      <td>L</td>
      <td>P</td>
      <td>L</td>
      <td>P</td>
      <td>L</td>
      <td>P</td>
      <td>L</td>
      <td>P</td>
      <td>L</td>
      <td>P</td>
      <td>L</td>
      <td>P</td>
      <td>L</td>
      <td>P</td>
      <td>L</td>
      <td>P</td>
      <td>L</td>
      <td>P</td>
      <td>L</td>
      <td>P</td>
      <td>L</td>
      <td>P</td>
      <td>L</td>
      <td>P</td>
      <td>L</td>
      <td>P</td>
      <td>L</td>
      <td>P</td>
      <td>L</td>
      <td>P</td>
      <td>L</td>
      <td>P</td>

      
      </tr>
  </thead>

  <tbody>


      <% @pasiens.each do |pasien| %>
      <tr>

          <td><%= pasien.nama_penyakit %></td>
          <td><%= pasien.jenis_penyakit %></td>
          <td><%= pasien.j1 %></td>
          <td><%= pasien.j2 %></td>
          <td><%= pasien.j3 %></td>
          <td><%= pasien.j4 %></td>
          <td><%= pasien.j5 %></td>
          <td><%= pasien.j6 %></td>
          <td><%= pasien.j7 %></td>
          <td><%= pasien.j8 %></td>
          <td><%= pasien.j9 %></td>
          <td><%= pasien.j10 %></td>
          <td><%= pasien.j11 %></td>
          <td><%= pasien.j12 %></td>
          <td><%= pasien.j13 %></td>
          <td><%= pasien.j14 %></td>
          <td><%= pasien.j15 %></td>
          <td><%= pasien.j16 %></td>
          <td><%= pasien.j17 %></td>
          <td><%= pasien.j18 %></td>
          <td><%= pasien.j19 %></td>
          <td><%= pasien.j20 %></td>
          <td><%= pasien.j21 %></td>
          <td><%= pasien.j22 %></td>
          <td><%= pasien.j23 %></td>
          <td><%= pasien.j24 %></td>
          <td><%= pasien.j25 %></td>
          <td><%= pasien.j26 %></td>
          <td><%= pasien.j27 %></td>
          <td><%= pasien.j28 %></td>
          <td><%= pasien.j29 %></td>
          <td><%= pasien.j30 %></td>
          <td><%= pasien.j31 %></td>
          <td><%= pasien.j32 %></td>
          <td><%= pasien.j33 %></td>
          <td><%= pasien.j34 %></td>
          <td><%= pasien.j35 %></td>
          <td><%= pasien.j36 %></td>
          <td><%= pasien.j37 %></td>
          <td><%= pasien.j38 %></td>
          <td><%= pasien.j39 %></td>
          <td><%= pasien.j40 %></td>

                    
          <% end %>

<!--        <td><%#<%= link_to 'Destroy', resep, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
          
      </tr>

    
  </tbody>
</table>

app/views/pasiens/new.html.erb
<%= render 'form' %>

app/views/pasiens/rekam_medik.html.erb
<h3 style="text-align: center;"> Puskesmas Kampung Sawah</h3>
<h4 style="text-align: center;"> Bandar Lampung </h4><br>

<div class="pull-center">
<h2 style="text-align: center;"> Kartu Status Pasien </h2>
</div>

 No RM : <%= @pasien.no_rm %> <br>
 Nama : <%= @pasien.nama %> <br>
 Umur : <%= @pasien.umur %> <br>
Jenis Kelamin : <%= @pasien.jenis_kelamin %> <br>
 <br>
<% if @pasien.rekam_mediks.any? %>
<div class="col-md-6 col-md-offset-2">
<table class="table" align="center" style="border-top: 1px solid black; border-right: 1px solid black; border-left: 1px solid black">
  <thead>
    <tr>
      <th style="border-bottom: 1px solid black; border-right: 1px solid black">Tanggal</th>
      <th style="border-bottom: 1px solid black; border-right: 1px solid black">Keluhan</th>
      <th style="border-bottom: 1px solid black; border-right: 1px solid black">Penyakit</th>
      <th style="border-bottom: 1px solid black; border-right: 1px solid black">Terapi</th>
      <th style="border-bottom: 1px solid black;">Tindakan</th>
    </tr>
  </thead>

  <tbody>
<% @pasien.rekam_mediks.each do |rm| %>
      
      <tr>
          <td style="border-bottom: 1px solid black; border-right: 1px solid black"><%= rm.created_at.to_date.to_s %></td>
          <td style="border-bottom: 1px solid black; border-right: 1px solid black"><%= rm.keluhan %></td>
          <td style="border-bottom: 1px solid black; border-right: 1px solid black"><%= rm.penyakit.nama %></td>
          <td style="border-bottom: 1px solid black; border-right: 1px solid black"><%= rm.terapi %></td>
          <td style="border-bottom: 1px solid black;"><%= rm.tindakan %></td>
          <% end %>
      </tr>
    </tbody>
</table>
</div>
<% end %>

app/views/pasiens/search.html.erb
<% if params[:search] %>

    <table class="table table-bordered">
      <thead vertical-align="middle">
        <tr>
          <th>No RM</th>
          <th>Nama</th>
          <th>Alamat</th>
          <th>Kelurahan</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @pasiens.each do |pasien| %>
            <tr>
            <td><%= pasien.no_rm %></td>
            <td><%= pasien.nama %></td>
            <td><%= pasien.alamat %></td>
            <td><%= pasien.kelurahan.nama%></td>
            <td><%= link_to 'Tambah', new_kunjungan_path(no_rm: pasien) %></td>
            </tr>
          <% end %>
        </tbody>
    </table>


<% else %>
    <%= form_tag(search_pasien_path, :method => "get", role: "search") do %>
    <div class="pull-right">
        <div class="form-group">
            <%= search_field_tag :search, params[:search], class: "form-control", placeholder: "Search Pasien" %>
            <%= submit_tag "Search", class: 'btn btn-info' %>
        </div>
    </div>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>No RM</th>
          <th>Nama</th>
          <th>Alamat</th>
          <th>Kelurahan</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
    <% @pasiens.each do |pasien| %>
            <tr>
            <td><%= pasien.no_rm %></td>
            <td><%= pasien.nama %></td>
            <td><%= pasien.alamat %></td>
            <td><%= pasien.kelurahan.nama%></td>
            <td><%= link_to 'Tambah', new_kunjungan_path(no_rm: pasien) %></td>
            </tr>
          <% end %>
        </tbody>
    </table>
<% end %>


<% end %>

app/views/pasiens/show.html.erb
<div class="row">
<div class="col-md-4">
    
<div class="panel panel-default" style="width: 350px;">
  <div class="panel-heading">
    <h3 class="panel-title">Keluarga Pasien</h3>
  </div>
  <div class="panel-body">
    
    <div class="row">
        <div class="col-md-7">
            <p><strong>Nama</strong></p>
            <p><% @keluarga.each do |keluarga| %>
                <%= link_to keluarga.nama, pasien_path(keluarga.id) %>                 
            </p>
            <% end %>
        </div>
        <div class="col-md-5">
            <p><strong>Status</strong></p>
            <p><% @keluarga.each do |keluarga| %>
                <%= keluarga.status %> keluarga                
            </p>
            <% end %>
        </div>
    </div><br>
    </div>
    </div>
    
    
    <div class="panel panel-default" style="width: 350px;">
  <div class="panel-heading">
    <h3 class="panel-title">Data Pasien</h3>
  </div>
  <div class="panel-body">
    
    <div class="row">
        <div class="col-md-4">
            <p><strong>No RM</strong></p>
            <p><strong>Nama</strong></p>
            <p><strong>Status Keluarga</strong></p>
            <p><strong>Alamat</strong></p>
            <p><strong>Kelurahan</strong></p>
            <p><strong>Umur</strong></p>
            <p><strong>Jenis Kelamin</strong></p>
            <p><strong>Kategori</strong></p>
            <p><strong>Jenis Kartu</strong></p>
            <p><strong>No Kartu</strong></p>
        </div>
        <div class="col-md-8">
            <p> : <%= @pasien.no_rm %></p>
            <p> : <%= @pasien.nama %></p>
            <p> : <%= @pasien.status %> keluarga</p>
            <p> : <%= @pasien.alamat %></p>
            <p> : <%= @pasien.kelurahan.nama %></p>
            <p> : <%= @pasien.umur %></p>
            <p> : <%= @pasien.jenis_kelamin %></p>
            <p> : <%= @pasien.kategori.nama %></p>
            <p> <% if @pasien.jenis_kartu != nil %>
                    : <%= @pasien.jenis_kartu.nama %>
                <% else %>
                    : -
                <% end %></p>
            <p> : <%= @pasien.no_kartu %></p>
        </div>
    </div>
    
</div> 

    </div>
    </div>
        
<div class="col-md-8">
<h4>Rekam Medik Pasien</h4>
    
    <div>
        <%= link_to 'Tambah rekam medik', new_rekam_medik_path(no_rm: @pasien) %>
    
        <div class="pull-right">
        <%= link_to "Cetak Rekam Medik", cetak_rekam_medik_path(id: @pasien, :format => "pdf"), :target => "_blank" %>
        </div>
    </div><br>

<% if @pasien.rekam_mediks.any? %>

<table class="table">
  <thead>
    <tr>
      <th>Tanggal</th>
      <th>Keluhan</th>
      <th>Penyakit</th>
      <th>Terapi</th>
      <th>Tindakan</th>
      <th>Dokter</th>
      <th colspan="2">Aksi</th>
    </tr>
  </thead>

  <tbody>
<% @pasien.rekam_mediks.each do |rm| %>
      
      <tr>
          <td><%= rm.created_at.to_date.to_s %></td>
          <td><%= rm.keluhan %></td>
          <td><%= rm.penyakit.nama %></td>
          <td><%= rm.terapi %></td>
          <td><%= rm.tindakan %></td>
          <% if rm.dokter != nil %>
          <td><%= rm.dokter.nama %></td>
          <% else %>
          <td>-</td>
          <% end %>
          <td><%= link_to 'Edit', edit_rekam_medik_path(rm.id) %></td>
          <td><%= link_to 'Destroy', rm, method: :delete, data: { confirm: 'Are you sure?' } %></td>


          <% end %>
      </tr>
    </tbody>
</table>
<% end %>
<!--<p id="pdf_link"><%#<%= link_to "Download Invoice (PDF)", pasien_path(@pasien, :format => "pdf") %></p>-->

    
    </div>
</div>
<%#<%= link_to 'Edit', edit_pasien_path(@pasien) %> 
<%#<%= link_to 'Back', pasiens_path %>

    