config/routes.rb
Rails.application.routes.draw do
    
  resources :dokters
  resources :transaksi_obats
  resources :obat_masuks
  resources :reseps
  resources :rekam_mediks
  resources :kunjungans
  resources :pasiens
  resources :kartu_rms
  resources :penyakits
  resources :obats
  resources :jenis_penyakits
  resources :jenis_kartus
  resources :kelurahans
  resources :polis
  resources :kategoris
    root 'sessions#new'

    get '/help' =>'static_pages#help'
    get '/home' =>'static_pages#home'
    get '/signup' => 'admins#new'
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    delete '/logout' => 'sessions#destroy'
    get 'search_pasien' => 'pasiens#search'
    get 'search_obat_masuk' => 'obats#search_obat_masuk'
    get 'search_obat_keluar' => 'obats#search_obat_keluar'
    get 'cetak_rekam_medik' => 'pasiens#rekam_medik'
    get 'lb2' => 'obats#laporan'
    get 'lb1' => 'pasiens#laporan'
    get 'cetak_lb1' => 'pasiens#cetak_laporan'
    get 'cetak_lb2' => 'obats#cetak_laporan'
  resources :admins

end

app/models/kategori.rb
class Kategori < ActiveRecord::Base
    has_many :jenis_kartus
    has_many :pasiens
    has_many :kunjungans
    
end

app/controllers/kategoris_controller.rb
class KategorisController < ApplicationController
  before_action :set_kategori, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:new, :create, :update, :destroy, :index, :show, :edit]

  # GET /kategoris
  # GET /kategoris.json
  def index
    @kategoris = Kategori.all
  end

  # GET /kategoris/1
  # GET /kategoris/1.json
  def show
  end

  # GET /kategoris/new
  def new
    @kategori = Kategori.new
  end

  # GET /kategoris/1/edit
  def edit
  end

  # POST /kategoris
  # POST /kategoris.json
  def create
    @kategori = Kategori.new(kategori_params)

    respond_to do |format|
      if @kategori.save
        format.html { redirect_to @kategori, notice: 'Kategori was successfully created.' }
        format.json { render :show, status: :created, location: @kategori }
      else
        format.html { render :new }
        format.json { render json: @kategori.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kategoris/1
  # PATCH/PUT /kategoris/1.json
  def update
    respond_to do |format|
      if @kategori.update(kategori_params)
        format.html { redirect_to @kategori, notice: 'Kategori was successfully updated.' }
        format.json { render :show, status: :ok, location: @kategori }
      else
        format.html { render :edit }
        format.json { render json: @kategori.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kategoris/1
  # DELETE /kategoris/1.json
  def destroy
    @kategori.destroy
    respond_to do |format|
      format.html { redirect_to kategoris_url, notice: 'Kategori was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kategori
      @kategori = Kategori.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kategori_params
      params.require(:kategori).permit(:nama)
    end
end

app/helpers/kategoris_helper.rb
module KategorisHelper
end

app/views/kategoris/_form.html.erb
<%= form_for(@kategori) do |f| %>
  <% if @kategori.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kategori.errors.count, "error") %> prohibited this kategori from being saved:</h2>

      <ul>
      <% @kategori.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nama %><br>
    <%= f.text_field :nama %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kategoris/edit.html.erb
<h1>Editing Kategori</h1>

<%= render 'form' %>

<%= link_to 'Show', @kategori %> |
<%= link_to 'Back', kategoris_path %>

app/views/kategoris/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Kategoris</h1>

<table>
  <thead>
    <tr>
      <th>Nama</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kategoris.each do |kategori| %>
      <tr>
        <td><%= kategori.nama %></td>
        <td><%= link_to 'Show', kategori %></td>
        <td><%= link_to 'Edit', edit_kategori_path(kategori) %></td>
        <td><%= link_to 'Destroy', kategori, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kategori', new_kategori_path %>

app/views/kategoris/new.html.erb
<h1>New Kategori</h1>

<%= render 'form' %>

<%= link_to 'Back', kategoris_path %>

app/views/kategoris/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nama:</strong>
  <%= @kategori.nama %>
</p>

<%= link_to 'Edit', edit_kategori_path(@kategori) %> |
<%= link_to 'Back', kategoris_path %>